### ISSUE TITLE
Add create function to all the tools class in the custom tools

### ISSUE THREAD

**Issue by prakashr7d** [Sayvai-io/custom-tools#47]

**Comment by Sanjaypranav** [comment]
ok noted

**Comment by prakashr7d** [comment]
Jaya done it… no worries


Prakash R
NLP researcher

mobile: +91 8870539376
Email: ***@***.***

[image: LinkedIn icon]
<https://www.linkedin.com/in/prakash-r-1636591ab/>  [image:
Instagram icon] <https://www.instagram.com/prakashr7d/>

**Comment by JayasuriyaE** [comment]
- [X] done with issue 
- [X] got reviewed 
- [X] working perfectly
